### PR TITLE
Some instructions

### PR DESCRIPTION
**Pull request by montlikadani**

### CODE REVIEW

**Comment by megoesrawr** [comment]
instructions for what?

**Comment by montlikadani** [comment]
To run this command, you would need CommandExecutor implements.

_This PR is not necessary to accept it unless it is needed._

**Comment by megoesrawr** [comment]
Ah. Ok.

**Comment by montlikadani** [comment]
It's weird, has it tested how it works?

**Comment by megoesrawr** [comment]
I did test it. It works fine with or without it oddly enough...

**Pull request merged**
