### PR TITLE
Update lwc_hu.properties file to the latest version

### PR DESCRIPTION
**Pull request by montlikadani**
I updated to the latest version.

**In the upcoming times, if possible, when adding new messages, you should include the strings in the message files to make the translator easier.**

### CODE REVIEW

**Comment by megoesrawr** [comment]
Added in 2.0.2

**Comment by montlikadani** [comment]
Merged?

**Comment by montlikadani** [comment]
**Please merge because it will not be displayed.** https://github.com/megoesrawr/LWCEntityLocking/blob/master/src/lang/lwc_hu.properties

**Comment by megoesrawr** [comment]
Oops. Sorry. I thought I added it.

**Pull request merged**
